name: App Test
on:
  pull_request:
    types: [opened, synchronize, reopened]

  jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup.Nodejs
        uses: action/setup-node@v4
        with:
          node-version: 18
      - name: Check version
        run: node -v
