name: App Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup.Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check version
        run: node -v
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: docker build  -t my-app .
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.4.0
        with:
          image-ref: my-app
          format: sarif
          sarif-output: trivy-scan.sarif
